### ISSUE TITLE
cv2.error

### ISSUE THREAD

**Issue by wulei878** [lmp31/BM3D-Denoise#1]
hi, I came across this error: "cv2.error: /Users/travis/build/skvark/opencv-python/opencv/modules/core/src/dxt.cpp:4154: error: (-213) Odd-size DCT's are not implemented in function apply", could you please help?

**Comment by liuhuang31** [comment]
hi,because it is a long time from me to upload the code.Are you changed the code in some ways?The problem maybe you image isn't a grayscale image?Or you need a 1 channel image float img for dct,note that dct needs float values in the [0..1] range.

**Comment by lmp31** [comment]
hi,because it is a long time from me to upload the code.Are you changed the code in some ways?The problem maybe you image isn't a grayscale image?Or you need a 1 channel image float img for dct,note that dct needs float values in the [0..1] range.

**Comment by serendipitYang** [comment]
I encountered the exactly same issue here, my image is definitely gray, but shaped 192*168. Moreover, if I ran a shaped 256*256, it worked fine.
