### ISSUE TITLE
PSNR is worse after second step

### ISSUE THREAD

**Issue by zaccharieramzi** [lmp31/BM3D-Denoise#2]
Hi,

I was trying your code and I got the following result:
```
The Processing time of the First step is 67.925459 s
The PSNR between the two img of the First step is 27.934267
The Processing time of the Second step is 121.617898 s
The PSNR between the two img of the Second step is 27.099832
The total Processing time is 189.543357 s
```
The PSNR decreased in the second step. Is this normal?

Have you compared the outputs of your code to the official Matlab implemtentation?

The image I used was barbara:
![barbara](https://user-images.githubusercontent.com/6387497/59689771-87e2cb80-91e0-11e9-980f-3d94a927a4ac.png)

**Comment by liuhuang31** [comment]
Hi,


The code was modified on the basis of someone else. I haven't compared the outputs of my code to the official Matlab implementation.


As for PSNR decreased in the second step, I am sorry, I just ran the code simply, can't remember a lot of details.




------------------
Best regards,


Huang Liu (刘煌)


College of Mathematics and Computer Science, Fuzhou University
