### ISSUE TITLE
Result different official matlab code

### ISSUE THREAD

**Issue by Ryanshuai** [lmp31/BM3D-Denoise#3]
您好，
你这个代码跑出来结果和matlab官方的那个代码结果不一样啊。
psnr少了4左右，然后输出图像差别也很大。
还打算更新嘛？
thanks~

**Comment by liuhuang31** [comment]
您好，之前在学校研究图像处理的时候，用的bm3d。后面转语音方向，就没怎么关注了，应该是不更新了。如果你熟悉matlab，可以对比一下那部分有差异。





------------------ Original ------------------

**Comment by Ryanshuai** [comment]
My implement
[https://github.com/Ryanshuai/BM3D_cpp2py](https://github.com/Ryanshuai/BM3D_cpp2py)

**Comment by liuhuang31** [comment]
Good job! BM3D is a good entry-level algorithm for beginners. Its useful.







Best regards,


Huang Liu


&nbsp;
